DEBUG = True

SECRET_KEY = 'TODO_____Ch4nge____with__your_own____key'

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_POOL_SIZE = 1
SQLALCHEMY_POOL_RECYCLE = 1
SQLALCHEMY_MAX_OVERFLOW = 1
SQLALCHEMY_DATABASE_URI = 'postgresql://USER:PWD@DB_HOST:6432/DB_NAME'
SQLALCHEMY_ECHO = True

REDIS_HOST = '172.17.0.2'
